#!/bin/sh

PRGNAM=copyagent
PACKNAM=copy_agent

VERSION=${VERSION:-3.2.01.0481}
BUILD=${BUILD:-1}
TAG=${TAG:-_tsst}

case "$( uname -m )" in
    i?86) ARCH=x86;echo 1 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
esac

CWD=$(pwd)
TMP=${TMP:-/tmp/SBo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT $TMP/$PACKNAM-$VERSION
cd $TMP/$PACKNAM-$VERSION
#rm -rf .$PRGNAM-dist
tar xvf $CWD/$PACKNAM-$VERSION.tgz
cd copy

chown -R root:root .
find -L . \
 \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 -o -perm 511 \) \
 -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
 -exec chmod 644 {} \;

mkdir $PKG/opt
cp -R $TMP/$PACKNAM-$VERSION/copy/$ARCH/ $PKG/opt/copyagent
install -D -m 644 $CWD/copyagent.desktop $PKG/usr/share/applications/copyagent.desktop
install -D -m 644 $CWD/copy-client.png $PKG/usr/share/icons/copy-client.png

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cat $TMP/$PACKNAM-$VERSION/copy/README > $PKG/usr/doc/$PRGNAM-$VERSION/README
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
cat $CWD/doinst.sh > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
